export const ADD_EVENT = "ADD EVENT";
export const UPDATE_EVENT = "UPDATE EVENT";
export const DELETE_EVENT = "DELETE EVENT";
export const FETCH_EVENTS = "FETCH_EVENTS";
export const LISTEN_TO_EVENT_CHAT = "LISTEN_TO_EVENT_CHAT";
export const CLEAR_COMMENTS = "CLEAR_COMMENTS"; 